version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_KEY=base64:YOUR_APP_KEY_HERE
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=muntag_db
            - DB_USERNAME=root
            - DB_PASSWORD=root_password
        depends_on:
            - db

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: muntag_db
            MYSQL_USER: muntag_user
            MYSQL_PASSWORD: user_password
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
